export const snacks = [
  {
    location: "11",
    item: "cola",
    price: 2.1,
    quantity: 5,
    img: "https://media.officedepot.com/image/upload/b_rgb:FFFFFF,c_pad,dpr_1.0,f_auto,h_1665,q_auto,w_1250/c_pad,h_1665,w_1250/v1/products/208206/208206_p?pgw=1&pgwact=1",
  },
  {
    location: "12",
    item: "Pepsi",
    price: 2.5,
    quantity: 5,
    img: "https://www.luluhypermarket.com/medias/424982-01.jpg-515Wx515H?context=bWFzdGVyfGltYWdlc3wxNzk0MDh8aW1hZ2UvanBlZ3xoYjcvaDZhLzk3NzU1NTIzMzE4MDYvNDI0OTgyLTAxLmpwZ181MTVXeDUxNUh8YzE5MDY0NTE5ODE3NWIyMjVmZjRmNGUyNTRjNTc5NTAzMDZjMTdmZjQwNjkxMjc5NzE0MjdiMDg3MTQwNjViYw",
  },
  {
    location: "13",
    item: "Sprite",
    price: 3.2,
    quantity: 5,
    img: "https://images-na.ssl-images-amazon.com/images/I/51AniJpRujL._SX425_.jpg",
  },
  {
    location: "14",
    item: "xl",
    price: 4,
    quantity: 5,
    img: "https://p.globalsources.com/IMAGES/PDT/B1177018977/XL-Energy-Drink.jpg",
  },
  {
    location: "15",
    item: "choco",
    price: 3,
    quantity: 5,
    img: "https://d2lnr5mha7bycj.cloudfront.net/product-image/file/large_3a2f1be3-95a5-438c-a0a1-684d8af8c647.jpg",
  },
  {
    location: "21",
    item: "lays",
    price: 1.6,
    quantity: 5,
    img: "https://target.scene7.com/is/image/Target/GUEST_bbe70005-2e20-4da5-baa1-1a8fdf544aa1?wid=488&hei=488&fmt=pjpeg",
  },
  {
    location: "22",
    item: "Cheetos",
    price: 3.70,
    quantity: 5,
    img: "https://www.myamericanmarket.com/4632-large_default/cheetos-crunchy-flamin-hot.jpg",
  },
  {
    location: "23",
    item: "lays",
    price: 1,
    quantity: 5,
    img: "https://www.hollandshop24.com/media/image/product/67/lg/lays-chips-naturel-xxxl-300g.jpg",
  },
  {
    location: "24",
    item: "lays",
    price: 1,
    quantity: 5,
    img: "https://sc02.alicdn.com/kf/U4a090acfc53e4e04b14b3fe82a19cb33p.jpg_640x640.jpg",
  },
  {
    location: "25",
    item: "lays",
    price: 1,
    quantity: 5,
    img: "https://images-na.ssl-images-amazon.com/images/I/71uQ3b9609L._SL1500_.jpg",
  },

  {
    location: "31",
    item: "galaxy",
    price: 3,
    quantity: 5,
    img: "https://images-na.ssl-images-amazon.com/images/I/51hREDB5-NL._SL1000_.jpg",
  },
  {
    location: "32",
    item: "snikers ",
    price: 2.2,
    quantity: 5,
    img: "http://www.dmbase.com/images/detailed/2/Snicker_vertical_v.jpg",
  },
  {
    location: "33",
    item: "bubbly",
    price: 4.5,
    quantity: 5,
    img: "https://images-na.ssl-images-amazon.com/images/I/41100DSTICL._SX425_.jpg",
  },
  {
    location: "34",
    item: "mars",
    price: 4,
    quantity: 5,
    img: "https://images-na.ssl-images-amazon.com/images/I/71-Fk-zdrkL._SX522_.jpg",
  },
  {
    location: "35",
    item: "twix",
    price: 3,
    quantity: 5,
    img: "https://p.kindpng.com/picc/s/769-7696022_twix-freetoedit-twix-spekulatius-hd-png-download.png",
  },

  {
    location: "41",
    item: "lays",
    price: 1.2,
    quantity: 5,
    img: "https://target.scene7.com/is/image/Target/GUEST_bbe70005-2e20-4da5-baa1-1a8fdf544aa1?wid=488&hei=488&fmt=pjpeg",
  },
  {
    location: "42",
    item: "Cheetos",
    price: 3,
    quantity: 5,
    img: "https://www.myamericanmarket.com/4632-large_default/cheetos-crunchy-flamin-hot.jpg",
  },
  {
    location: "43",
    item: "lays",
    price: 1,
    quantity: 5,
    img: "https://www.hollandshop24.com/media/image/product/67/lg/lays-chips-naturel-xxxl-300g.jpg",
  },
  {
    location: "44",
    item: "lays",
    price: 1,
    quantity: 5,
    img: "https://sc02.alicdn.com/kf/U4a090acfc53e4e04b14b3fe82a19cb33p.jpg_640x640.jpg",
  },
  {
    location: "45",
    item: "lays",
    price: 1.3,
    quantity: 5,
    img: "https://images-na.ssl-images-amazon.com/images/I/71uQ3b9609L._SL1500_.jpg",
  },

  {
    location: "51",
    item: "fanta",
    price: 2.50,
    quantity: 5,
    img: "https://pizzahousealmere.nl/wp-content/uploads/2020/02/Fanta-orange-canada.png",
  },
  {
    location: "52",
    item: "Pepsi",
    price: 2,
    quantity: 5,
    img: "https://www.luluhypermarket.com/medias/424982-01.jpg-515Wx515H?context=bWFzdGVyfGltYWdlc3wxNzk0MDh8aW1hZ2UvanBlZ3xoYjcvaDZhLzk3NzU1NTIzMzE4MDYvNDI0OTgyLTAxLmpwZ181MTVXeDUxNUh8YzE5MDY0NTE5ODE3NWIyMjVmZjRmNGUyNTRjNTc5NTAzMDZjMTdmZjQwNjkxMjc5NzE0MjdiMDg3MTQwNjViYw",
  },
  {
    location: "53",
    item: "Sprite",
    price: 3,
    quantity: 2,
    img: "https://images-na.ssl-images-amazon.com/images/I/51AniJpRujL._SX425_.jpg",
  },
  {
    location: "54",
    item: "xl",
    price: 4,
    quantity: 5,
    img: "https://p.globalsources.com/IMAGES/PDT/B1177018977/XL-Energy-Drink.jpg",
  },
  {
    location: "55",
    item: "choco",
    price: 3,
    quantity: 5,
    img: "https://d2lnr5mha7bycj.cloudfront.net/product-image/file/large_3a2f1be3-95a5-438c-a0a1-684d8af8c647.jpg",
  },
];
